approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
    - ia32
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.18.0.cjs
